server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        add_header Blazor-Environment ${ASPNETCORE_ENVIRONMENT};
        try_files $uri $uri/ /index.html;
    }

    # Prevent caching of configuration and boot files
    location ~* \.(json|boot\.json|js)$ {
        add_header Blazor-Environment ${ASPNETCORE_ENVIRONMENT};
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        expires 0;
        try_files $uri =404;
    }
}