name: Build API image on push to develop/main, check which branch is the source →

on:
  push:
    branches: [develop, main, New-kind-of-github-workflow, FEAT/New-kind-of-github-workflow]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & push API image
        run: |
          if [ "${{ github.ref_name }}" != "develop" ]; then
            TAG=prod
          else
            TAG=acc
          fi

          docker build -f API/Dockerfile -t ghcr.io/ivar418/cine.net/api:$TAG .
          docker push ghcr.io/ivar418/cine.net/api:$TAG
